numero = int(input('Digite um numero: '))
n=1
print('{} x {} = {}'.format(numero, n, numero*n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero*n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero**n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero*n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero*n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero*n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero*n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero*n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero*n))
n=n+1
print('{} x {} = {}'.format(numero, n, numero*n))